export const GET_ALL_VIDEO_THUMBS = 'GET_ALL_VIDEO_THUMBS';
export const GET_ALL_FAVOURITE_VIDEO_THUMBS = 'GET_ALL_FAVOURITE_VIDEO_THUMBS';
export const GET_META = 'GET_META';
export const UPDATE_META = 'UPDATE_META';
